# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('apellidos', models.CharField(blank=True, max_length=30)),
                ('dni', models.CharField(max_length=9, verbose_name='DNI')),
                ('f_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de naciemiento')),
                ('direccion', models.CharField(blank=True, max_length=30)),
                ('localidad', models.CharField(blank=True, max_length=20)),
                ('cod_postal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código postal')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Sin especificar', 'Sin especificar')], default='Sin especificar', max_length=16)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clientes/')),
            ],
        ),
    ]
