# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('gestion_proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=30)),
                ('localidad', models.CharField(blank=True, max_length=20)),
                ('pais', models.CharField(blank=True, max_length=20)),
                ('cod_postal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código postal')),
                ('telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('fax', models.CharField(blank=True, max_length=9, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='proveedores/')),
            ],
        ),
    ]
