# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('gestion_stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('codigo', models.CharField(blank=True, max_length=30, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('marca', models.CharField(blank=True, max_length=30)),
                ('modelo', models.CharField(blank=True, max_length=30)),
                ('precio', models.FloatField(verbose_name='Precio (EUR)')),
                ('descripcion', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripción')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='stock/')),
            ],
        ),
    ]
